{% set name = "anys" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56c04f76afe5379a5058aec067befa1fb93070d63cabbd342e04b3d5aff739f8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7

test:
  requires:
    - pytest
    - pytest-cov
  source_files:
    - test
    - tox.ini
  imports:
    - anys
  commands:
    - python -m pytest -vv test

about:
  home: https://github.com/jwodder/anys
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Matchers for pytest
  dev_url: https://github.com/jwodder/anys

extra:
  recipe-maintainers:
    - jwodder
