{% set name = "anys" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5bcda88fcc490eda840a247c8c18b7a350051f530c288ad530e94c8d139602de

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7

test:
  requires:
    - pytest
    - pytest-cov
  source_files:
    - test
    - tox.ini
  imports:
    - anys
  commands:
    - python -m pytest -vv test

about:
  home: https://github.com/jwodder/anys
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Matchers for pytest
  dev_url: https://github.com/jwodder/anys

extra:
  recipe-maintainers:
    - jwodder
